/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dictionary;

import java.awt.Cursor;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.ImageIcon;
/**
 *
 * @author isyed
 */
public class OnlineGuideFrame extends javax.swing.JFrame {

    /**
     * Creates new form OnlineGuideFrame
     */
    public OnlineGuideFrame(boolean check) {
        setVisible(check);
        initComponents();
        icon = new ImageIcon("src\\dictionary\\Eng-to-Eng-Dictionary-Icon.jpg");
        setIconImage(icon.getImage());
        setTitle("Online Guide");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainHeading = new javax.swing.JLabel();
        mainHeading1 = new javax.swing.JLabel();
        courseButton2 = new javax.swing.JButton();
        courseButton1 = new javax.swing.JButton();
        guideButton3 = new javax.swing.JButton();
        guideButton1 = new javax.swing.JButton();
        guideButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mainHeading.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        mainHeading.setText("English - to - English Dictionary");
        mainHeading.setToolTipText("");

        mainHeading1.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        mainHeading1.setText("Online Guide");
        mainHeading1.setToolTipText("");

        courseButton2.setText("English Courses from EdX.org");
        courseButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                courseButton2MouseEntered(evt);
            }
        });
        courseButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseButton2ActionPerformed(evt);
            }
        });

        courseButton1.setText("English Courses from Coursera.org");
        courseButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                courseButton1MouseEntered(evt);
            }
        });
        courseButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseButton1ActionPerformed(evt);
            }
        });

        guideButton3.setText("Thesaurus");
        guideButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guideButton3MouseEntered(evt);
            }
        });
        guideButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guideButton3ActionPerformed(evt);
            }
        });

        guideButton1.setText("Merriam Webster");
        guideButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guideButton1MouseEntered(evt);
            }
        });
        guideButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guideButton1ActionPerformed(evt);
            }
        });

        guideButton2.setText("Google Translate");
        guideButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                guideButton2MouseEntered(evt);
            }
        });
        guideButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guideButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainHeading1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guideButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guideButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guideButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainHeading1)
                .addGap(22, 22, 22)
                .addComponent(courseButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(courseButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(guideButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(guideButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(guideButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void courseButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseButton1ActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URI("https://www.coursera.org/browse/language-learning/learning-english"));   
        } 
        catch (IOException | URISyntaxException e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_courseButton1ActionPerformed

    private void courseButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseButton1MouseEntered
        // TODO add your handling code here:
        courseButton1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_courseButton1MouseEntered

    private void courseButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseButton2ActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URI("https://www.edx.org/learn/english"));    
        } 
        catch (IOException | URISyntaxException e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_courseButton2ActionPerformed

    private void courseButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseButton2MouseEntered
        // TODO add your handling code here:
        courseButton2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_courseButton2MouseEntered

    private void guideButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guideButton1ActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URI("https://www.merriam-webster.com/"));
        } 
        catch (IOException | URISyntaxException e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_guideButton1ActionPerformed

    private void guideButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guideButton1MouseEntered
        // TODO add your handling code here:
        guideButton1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_guideButton1MouseEntered

    private void guideButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guideButton2ActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URI("https://translate.google.com/"));   
        } 
        catch (IOException | URISyntaxException e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_guideButton2ActionPerformed

    private void guideButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guideButton2MouseEntered
        // TODO add your handling code here:
        guideButton2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_guideButton2MouseEntered

    private void guideButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guideButton3ActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().browse(new URI("https://www.thesaurus.com/")); 
        } 
        catch (IOException | URISyntaxException e1) {
            e1.printStackTrace();
        }
    }//GEN-LAST:event_guideButton3ActionPerformed

    private void guideButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guideButton3MouseEntered
        // TODO add your handling code here:
        guideButton3.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_guideButton3MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OnlineGuideFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OnlineGuideFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OnlineGuideFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OnlineGuideFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OnlineGuideFrame(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton courseButton1;
    private javax.swing.JButton courseButton2;
    private javax.swing.JButton guideButton1;
    private javax.swing.JButton guideButton2;
    private javax.swing.JButton guideButton3;
    private javax.swing.JLabel mainHeading;
    private javax.swing.JLabel mainHeading1;
    // End of variables declaration//GEN-END:variables
    private ImageIcon icon;
}
